# Generated by Django 4.1.7 on 2023-02-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg_tb',
            new_name='register_tb',
        ),
    ]
