# Generated by Django 4.1.5 on 2023-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0005_rename_namr_contact_tb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
