# Generated by Django 4.1.5 on 2023-03-08 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0007_contactf_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_tb',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product/'),
            preserve_default=False,
        ),
    ]
