# Generated by Django 4.1.5 on 2023-03-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0009_getin_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
